window.esdocSearchIndex = [
  [
    "sboljs/lib_docs/collection.js~collection",
    "class/lib_docs/Collection.js~Collection.html",
    "<span>Collection</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Collection.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/component.js~component",
    "class/lib_docs/Component.js~Component.html",
    "<span>Component</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Component.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/componentdefinition.js~componentdefinition",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html",
    "<span>ComponentDefinition</span> <span class=\"search-result-import-path\">sboljs/lib_docs/ComponentDefinition.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/cut.js~cut",
    "class/lib_docs/Cut.js~Cut.html",
    "<span>Cut</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Cut.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/functionalcomponent.js~functionalcomponent",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html",
    "<span>FunctionalComponent</span> <span class=\"search-result-import-path\">sboljs/lib_docs/FunctionalComponent.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/genericlocation.js~genericlocation",
    "class/lib_docs/GenericLocation.js~GenericLocation.html",
    "<span>GenericLocation</span> <span class=\"search-result-import-path\">sboljs/lib_docs/GenericLocation.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/identified.js~identified",
    "class/lib_docs/Identified.js~Identified.html",
    "<span>Identified</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Identified.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/interaction.js~interaction",
    "class/lib_docs/Interaction.js~Interaction.html",
    "<span>Interaction</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Interaction.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/mapsto.js~mapsto",
    "class/lib_docs/MapsTo.js~MapsTo.html",
    "<span>MapsTo</span> <span class=\"search-result-import-path\">sboljs/lib_docs/MapsTo.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/model.js~model",
    "class/lib_docs/Model.js~Model.html",
    "<span>Model</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Model.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/module.js~module",
    "class/lib_docs/Module.js~Module.html",
    "<span>Module</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Module.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/moduledefinition.js~moduledefinition",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html",
    "<span>ModuleDefinition</span> <span class=\"search-result-import-path\">sboljs/lib_docs/ModuleDefinition.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/participation.js~participation",
    "class/lib_docs/Participation.js~Participation.html",
    "<span>Participation</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Participation.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/range.js~range",
    "class/lib_docs/Range.js~Range.html",
    "<span>Range</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Range.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/sboldocument.js~sboldocument",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html",
    "<span>SBOLDocument</span> <span class=\"search-result-import-path\">sboljs/lib_docs/SBOLDocument.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/sequence.js~sequence",
    "class/lib_docs/Sequence.js~Sequence.html",
    "<span>Sequence</span> <span class=\"search-result-import-path\">sboljs/lib_docs/Sequence.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/sequenceannotation.js~sequenceannotation",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html",
    "<span>SequenceAnnotation</span> <span class=\"search-result-import-path\">sboljs/lib_docs/SequenceAnnotation.js</span>",
    "class"
  ],
  [
    "sboljs/lib_docs/sequenceconstraint.js~sequenceconstraint",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html",
    "<span>SequenceConstraint</span> <span class=\"search-result-import-path\">sboljs/lib_docs/SequenceConstraint.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib_docs/collection.js",
    "file/lib_docs/Collection.js.html",
    "lib_docs/Collection.js",
    "file"
  ],
  [
    "lib_docs/collection.js~collection#constructor",
    "class/lib_docs/Collection.js~Collection.html#instance-constructor-constructor",
    "lib_docs/Collection.js~Collection#constructor",
    "method"
  ],
  [
    "lib_docs/component.js",
    "file/lib_docs/Component.js.html",
    "lib_docs/Component.js",
    "file"
  ],
  [
    "lib_docs/component.js~component#access",
    "class/lib_docs/Component.js~Component.html#instance-get-access",
    "lib_docs/Component.js~Component#access",
    "member"
  ],
  [
    "lib_docs/component.js~component#access",
    "class/lib_docs/Component.js~Component.html#instance-set-access",
    "lib_docs/Component.js~Component#access",
    "member"
  ],
  [
    "lib_docs/component.js~component#constructor",
    "class/lib_docs/Component.js~Component.html#instance-constructor-constructor",
    "lib_docs/Component.js~Component#constructor",
    "method"
  ],
  [
    "lib_docs/component.js~component#definition",
    "class/lib_docs/Component.js~Component.html#instance-set-definition",
    "lib_docs/Component.js~Component#definition",
    "member"
  ],
  [
    "lib_docs/component.js~component#definition",
    "class/lib_docs/Component.js~Component.html#instance-get-definition",
    "lib_docs/Component.js~Component#definition",
    "member"
  ],
  [
    "lib_docs/component.js~component#link",
    "class/lib_docs/Component.js~Component.html#instance-method-link",
    "lib_docs/Component.js~Component#link",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js",
    "file/lib_docs/ComponentDefinition.js.html",
    "lib_docs/ComponentDefinition.js",
    "file"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#addcomponent",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-addComponent",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#addComponent",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#addrole",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-addRole",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#addRole",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#addsequence",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-addSequence",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#addSequence",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#addsequenceannotation",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-addSequenceAnnotation",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#addSequenceAnnotation",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#addsequenceconstraint",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-addSequenceConstraint",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#addSequenceConstraint",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#addtype",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-addType",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#addType",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#components",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-get-components",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#components",
    "member"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#constructor",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-constructor-constructor",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#constructor",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#link",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-method-link",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#link",
    "method"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#roles",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-get-roles",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#roles",
    "member"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#sequenceannotations",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-get-sequenceAnnotations",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#sequenceAnnotations",
    "member"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#sequenceconstraints",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-get-sequenceConstraints",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#sequenceConstraints",
    "member"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#sequences",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-get-sequences",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#sequences",
    "member"
  ],
  [
    "lib_docs/componentdefinition.js~componentdefinition#types",
    "class/lib_docs/ComponentDefinition.js~ComponentDefinition.html#instance-get-types",
    "lib_docs/ComponentDefinition.js~ComponentDefinition#types",
    "member"
  ],
  [
    "lib_docs/cut.js",
    "file/lib_docs/Cut.js.html",
    "lib_docs/Cut.js",
    "file"
  ],
  [
    "lib_docs/cut.js~cut#at",
    "class/lib_docs/Cut.js~Cut.html#instance-get-at",
    "lib_docs/Cut.js~Cut#at",
    "member"
  ],
  [
    "lib_docs/cut.js~cut#at",
    "class/lib_docs/Cut.js~Cut.html#instance-set-at",
    "lib_docs/Cut.js~Cut#at",
    "member"
  ],
  [
    "lib_docs/cut.js~cut#constructor",
    "class/lib_docs/Cut.js~Cut.html#instance-constructor-constructor",
    "lib_docs/Cut.js~Cut#constructor",
    "method"
  ],
  [
    "lib_docs/cut.js~cut#orientation",
    "class/lib_docs/Cut.js~Cut.html#instance-get-orientation",
    "lib_docs/Cut.js~Cut#orientation",
    "member"
  ],
  [
    "lib_docs/cut.js~cut#orientation",
    "class/lib_docs/Cut.js~Cut.html#instance-set-orientation",
    "lib_docs/Cut.js~Cut#orientation",
    "member"
  ],
  [
    "lib_docs/functionalcomponent.js",
    "file/lib_docs/FunctionalComponent.js.html",
    "lib_docs/FunctionalComponent.js",
    "file"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#access",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-get-access",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#access",
    "member"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#access",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-set-access",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#access",
    "member"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#constructor",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-constructor-constructor",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#constructor",
    "method"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#definition",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-set-definition",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#definition",
    "member"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#definition",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-get-definition",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#definition",
    "member"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#direction",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-set-direction",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#direction",
    "member"
  ],
  [
    "lib_docs/functionalcomponent.js~functionalcomponent#direction",
    "class/lib_docs/FunctionalComponent.js~FunctionalComponent.html#instance-get-direction",
    "lib_docs/FunctionalComponent.js~FunctionalComponent#direction",
    "member"
  ],
  [
    "lib_docs/genericlocation.js",
    "file/lib_docs/GenericLocation.js.html",
    "lib_docs/GenericLocation.js",
    "file"
  ],
  [
    "lib_docs/genericlocation.js~genericlocation#constructor",
    "class/lib_docs/GenericLocation.js~GenericLocation.html#instance-constructor-constructor",
    "lib_docs/GenericLocation.js~GenericLocation#constructor",
    "method"
  ],
  [
    "lib_docs/genericlocation.js~genericlocation#orientation",
    "class/lib_docs/GenericLocation.js~GenericLocation.html#instance-get-orientation",
    "lib_docs/GenericLocation.js~GenericLocation#orientation",
    "member"
  ],
  [
    "lib_docs/genericlocation.js~genericlocation#orientation",
    "class/lib_docs/GenericLocation.js~GenericLocation.html#instance-set-orientation",
    "lib_docs/GenericLocation.js~GenericLocation#orientation",
    "member"
  ],
  [
    "lib_docs/identified.js",
    "file/lib_docs/Identified.js.html",
    "lib_docs/Identified.js",
    "file"
  ],
  [
    "lib_docs/identified.js~identified#addannotation",
    "class/lib_docs/Identified.js~Identified.html#instance-method-addAnnotation",
    "lib_docs/Identified.js~Identified#addAnnotation",
    "method"
  ],
  [
    "lib_docs/identified.js~identified#annotations",
    "class/lib_docs/Identified.js~Identified.html#instance-get-annotations",
    "lib_docs/Identified.js~Identified#annotations",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#constructor",
    "class/lib_docs/Identified.js~Identified.html#instance-constructor-constructor",
    "lib_docs/Identified.js~Identified#constructor",
    "method"
  ],
  [
    "lib_docs/identified.js~identified#description",
    "class/lib_docs/Identified.js~Identified.html#instance-set-description",
    "lib_docs/Identified.js~Identified#description",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#description",
    "class/lib_docs/Identified.js~Identified.html#instance-get-description",
    "lib_docs/Identified.js~Identified#description",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#displayid",
    "class/lib_docs/Identified.js~Identified.html#instance-set-displayId",
    "lib_docs/Identified.js~Identified#displayId",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#displayid",
    "class/lib_docs/Identified.js~Identified.html#instance-get-displayId",
    "lib_docs/Identified.js~Identified#displayId",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#getannotation",
    "class/lib_docs/Identified.js~Identified.html#instance-method-getAnnotation",
    "lib_docs/Identified.js~Identified#getAnnotation",
    "method"
  ],
  [
    "lib_docs/identified.js~identified#getannotations",
    "class/lib_docs/Identified.js~Identified.html#instance-method-getAnnotations",
    "lib_docs/Identified.js~Identified#getAnnotations",
    "method"
  ],
  [
    "lib_docs/identified.js~identified#name",
    "class/lib_docs/Identified.js~Identified.html#instance-set-name",
    "lib_docs/Identified.js~Identified#name",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#name",
    "class/lib_docs/Identified.js~Identified.html#instance-get-name",
    "lib_docs/Identified.js~Identified#name",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#persistentidentity",
    "class/lib_docs/Identified.js~Identified.html#instance-get-persistentIdentity",
    "lib_docs/Identified.js~Identified#persistentIdentity",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#persistentidentity",
    "class/lib_docs/Identified.js~Identified.html#instance-set-persistentIdentity",
    "lib_docs/Identified.js~Identified#persistentIdentity",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#uri",
    "class/lib_docs/Identified.js~Identified.html#instance-set-uri",
    "lib_docs/Identified.js~Identified#uri",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#uri",
    "class/lib_docs/Identified.js~Identified.html#instance-get-uri",
    "lib_docs/Identified.js~Identified#uri",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#version",
    "class/lib_docs/Identified.js~Identified.html#instance-get-version",
    "lib_docs/Identified.js~Identified#version",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#version",
    "class/lib_docs/Identified.js~Identified.html#instance-set-version",
    "lib_docs/Identified.js~Identified#version",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#wasderivedfrom",
    "class/lib_docs/Identified.js~Identified.html#instance-set-wasDerivedFrom",
    "lib_docs/Identified.js~Identified#wasDerivedFrom",
    "member"
  ],
  [
    "lib_docs/identified.js~identified#wasderivedfrom",
    "class/lib_docs/Identified.js~Identified.html#instance-get-wasDerivedFrom",
    "lib_docs/Identified.js~Identified#wasDerivedFrom",
    "member"
  ],
  [
    "lib_docs/interaction.js",
    "file/lib_docs/Interaction.js.html",
    "lib_docs/Interaction.js",
    "file"
  ],
  [
    "lib_docs/interaction.js~interaction#addparticipation",
    "class/lib_docs/Interaction.js~Interaction.html#instance-method-addParticipation",
    "lib_docs/Interaction.js~Interaction#addParticipation",
    "method"
  ],
  [
    "lib_docs/interaction.js~interaction#addtype",
    "class/lib_docs/Interaction.js~Interaction.html#instance-method-addType",
    "lib_docs/Interaction.js~Interaction#addType",
    "method"
  ],
  [
    "lib_docs/interaction.js~interaction#constructor",
    "class/lib_docs/Interaction.js~Interaction.html#instance-constructor-constructor",
    "lib_docs/Interaction.js~Interaction#constructor",
    "method"
  ],
  [
    "lib_docs/interaction.js~interaction#link",
    "class/lib_docs/Interaction.js~Interaction.html#instance-method-link",
    "lib_docs/Interaction.js~Interaction#link",
    "method"
  ],
  [
    "lib_docs/interaction.js~interaction#participations",
    "class/lib_docs/Interaction.js~Interaction.html#instance-get-participations",
    "lib_docs/Interaction.js~Interaction#participations",
    "member"
  ],
  [
    "lib_docs/interaction.js~interaction#types",
    "class/lib_docs/Interaction.js~Interaction.html#instance-get-types",
    "lib_docs/Interaction.js~Interaction#types",
    "member"
  ],
  [
    "lib_docs/mapsto.js",
    "file/lib_docs/MapsTo.js.html",
    "lib_docs/MapsTo.js",
    "file"
  ],
  [
    "lib_docs/mapsto.js~mapsto#constructor",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-constructor-constructor",
    "lib_docs/MapsTo.js~MapsTo#constructor",
    "method"
  ],
  [
    "lib_docs/mapsto.js~mapsto#link",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-method-link",
    "lib_docs/MapsTo.js~MapsTo#link",
    "method"
  ],
  [
    "lib_docs/mapsto.js~mapsto#local",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-set-local",
    "lib_docs/MapsTo.js~MapsTo#local",
    "member"
  ],
  [
    "lib_docs/mapsto.js~mapsto#local",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-get-local",
    "lib_docs/MapsTo.js~MapsTo#local",
    "member"
  ],
  [
    "lib_docs/mapsto.js~mapsto#refinement",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-get-refinement",
    "lib_docs/MapsTo.js~MapsTo#refinement",
    "member"
  ],
  [
    "lib_docs/mapsto.js~mapsto#refinement",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-set-refinement",
    "lib_docs/MapsTo.js~MapsTo#refinement",
    "member"
  ],
  [
    "lib_docs/mapsto.js~mapsto#remote",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-get-remote",
    "lib_docs/MapsTo.js~MapsTo#remote",
    "member"
  ],
  [
    "lib_docs/mapsto.js~mapsto#remote",
    "class/lib_docs/MapsTo.js~MapsTo.html#instance-set-remote",
    "lib_docs/MapsTo.js~MapsTo#remote",
    "member"
  ],
  [
    "lib_docs/model.js",
    "file/lib_docs/Model.js.html",
    "lib_docs/Model.js",
    "file"
  ],
  [
    "lib_docs/model.js~model#constructor",
    "class/lib_docs/Model.js~Model.html#instance-constructor-constructor",
    "lib_docs/Model.js~Model#constructor",
    "method"
  ],
  [
    "lib_docs/model.js~model#framework",
    "class/lib_docs/Model.js~Model.html#instance-get-framework",
    "lib_docs/Model.js~Model#framework",
    "member"
  ],
  [
    "lib_docs/model.js~model#framework",
    "class/lib_docs/Model.js~Model.html#instance-set-framework",
    "lib_docs/Model.js~Model#framework",
    "member"
  ],
  [
    "lib_docs/model.js~model#language",
    "class/lib_docs/Model.js~Model.html#instance-get-language",
    "lib_docs/Model.js~Model#language",
    "member"
  ],
  [
    "lib_docs/model.js~model#language",
    "class/lib_docs/Model.js~Model.html#instance-set-language",
    "lib_docs/Model.js~Model#language",
    "member"
  ],
  [
    "lib_docs/model.js~model#source",
    "class/lib_docs/Model.js~Model.html#instance-get-source",
    "lib_docs/Model.js~Model#source",
    "member"
  ],
  [
    "lib_docs/model.js~model#source",
    "class/lib_docs/Model.js~Model.html#instance-set-source",
    "lib_docs/Model.js~Model#source",
    "member"
  ],
  [
    "lib_docs/module.js",
    "file/lib_docs/Module.js.html",
    "lib_docs/Module.js",
    "file"
  ],
  [
    "lib_docs/module.js~module#addmapping",
    "class/lib_docs/Module.js~Module.html#instance-method-addMapping",
    "lib_docs/Module.js~Module#addMapping",
    "method"
  ],
  [
    "lib_docs/module.js~module#constructor",
    "class/lib_docs/Module.js~Module.html#instance-constructor-constructor",
    "lib_docs/Module.js~Module#constructor",
    "method"
  ],
  [
    "lib_docs/module.js~module#definition",
    "class/lib_docs/Module.js~Module.html#instance-get-definition",
    "lib_docs/Module.js~Module#definition",
    "member"
  ],
  [
    "lib_docs/module.js~module#definition",
    "class/lib_docs/Module.js~Module.html#instance-set-definition",
    "lib_docs/Module.js~Module#definition",
    "member"
  ],
  [
    "lib_docs/module.js~module#link",
    "class/lib_docs/Module.js~Module.html#instance-method-link",
    "lib_docs/Module.js~Module#link",
    "method"
  ],
  [
    "lib_docs/module.js~module#mappings",
    "class/lib_docs/Module.js~Module.html#instance-get-mappings",
    "lib_docs/Module.js~Module#mappings",
    "member"
  ],
  [
    "lib_docs/moduledefinition.js",
    "file/lib_docs/ModuleDefinition.js.html",
    "lib_docs/ModuleDefinition.js",
    "file"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#addfunctionalcomponent",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-method-addFunctionalComponent",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#addFunctionalComponent",
    "method"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#addinteraction",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-method-addInteraction",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#addInteraction",
    "method"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#addmodule",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-method-addModule",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#addModule",
    "method"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#addrole",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-method-addRole",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#addRole",
    "method"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#constructor",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-constructor-constructor",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#constructor",
    "method"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#functionalcomponents",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-get-functionalComponents",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#functionalComponents",
    "member"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#interactions",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-get-interactions",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#interactions",
    "member"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#link",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-method-link",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#link",
    "method"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#modules",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-get-modules",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#modules",
    "member"
  ],
  [
    "lib_docs/moduledefinition.js~moduledefinition#roles",
    "class/lib_docs/ModuleDefinition.js~ModuleDefinition.html#instance-get-roles",
    "lib_docs/ModuleDefinition.js~ModuleDefinition#roles",
    "member"
  ],
  [
    "lib_docs/participation.js",
    "file/lib_docs/Participation.js.html",
    "lib_docs/Participation.js",
    "file"
  ],
  [
    "lib_docs/participation.js~participation#addparticipant",
    "class/lib_docs/Participation.js~Participation.html#instance-method-addParticipant",
    "lib_docs/Participation.js~Participation#addParticipant",
    "method"
  ],
  [
    "lib_docs/participation.js~participation#addrole",
    "class/lib_docs/Participation.js~Participation.html#instance-method-addRole",
    "lib_docs/Participation.js~Participation#addRole",
    "method"
  ],
  [
    "lib_docs/participation.js~participation#constructor",
    "class/lib_docs/Participation.js~Participation.html#instance-constructor-constructor",
    "lib_docs/Participation.js~Participation#constructor",
    "method"
  ],
  [
    "lib_docs/participation.js~participation#link",
    "class/lib_docs/Participation.js~Participation.html#instance-method-link",
    "lib_docs/Participation.js~Participation#link",
    "method"
  ],
  [
    "lib_docs/participation.js~participation#participants",
    "class/lib_docs/Participation.js~Participation.html#instance-get-participants",
    "lib_docs/Participation.js~Participation#participants",
    "member"
  ],
  [
    "lib_docs/participation.js~participation#roles",
    "class/lib_docs/Participation.js~Participation.html#instance-get-roles",
    "lib_docs/Participation.js~Participation#roles",
    "member"
  ],
  [
    "lib_docs/range.js",
    "file/lib_docs/Range.js.html",
    "lib_docs/Range.js",
    "file"
  ],
  [
    "lib_docs/range.js~range#constructor",
    "class/lib_docs/Range.js~Range.html#instance-constructor-constructor",
    "lib_docs/Range.js~Range#constructor",
    "method"
  ],
  [
    "lib_docs/range.js~range#end",
    "class/lib_docs/Range.js~Range.html#instance-set-end",
    "lib_docs/Range.js~Range#end",
    "member"
  ],
  [
    "lib_docs/range.js~range#end",
    "class/lib_docs/Range.js~Range.html#instance-get-end",
    "lib_docs/Range.js~Range#end",
    "member"
  ],
  [
    "lib_docs/range.js~range#orientation",
    "class/lib_docs/Range.js~Range.html#instance-get-orientation",
    "lib_docs/Range.js~Range#orientation",
    "member"
  ],
  [
    "lib_docs/range.js~range#orientation",
    "class/lib_docs/Range.js~Range.html#instance-set-orientation",
    "lib_docs/Range.js~Range#orientation",
    "member"
  ],
  [
    "lib_docs/range.js~range#start",
    "class/lib_docs/Range.js~Range.html#instance-get-start",
    "lib_docs/Range.js~Range#start",
    "member"
  ],
  [
    "lib_docs/range.js~range#start",
    "class/lib_docs/Range.js~Range.html#instance-set-start",
    "lib_docs/Range.js~Range#start",
    "member"
  ],
  [
    "lib_docs/sboldocument.js",
    "file/lib_docs/SBOLDocument.js.html",
    "lib_docs/SBOLDocument.js",
    "file"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#collection",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-collection",
    "lib_docs/SBOLDocument.js~SBOLDocument#collection",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#component",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-component",
    "lib_docs/SBOLDocument.js~SBOLDocument#component",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#componentdefinition",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-componentDefinition",
    "lib_docs/SBOLDocument.js~SBOLDocument#componentDefinition",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#componentdefinitions",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-componentDefinitions",
    "lib_docs/SBOLDocument.js~SBOLDocument#componentDefinitions",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#components",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-components",
    "lib_docs/SBOLDocument.js~SBOLDocument#components",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#constructor",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-constructor-constructor",
    "lib_docs/SBOLDocument.js~SBOLDocument#constructor",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#cut",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-cut",
    "lib_docs/SBOLDocument.js~SBOLDocument#cut",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#functionalcomponent",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-functionalComponent",
    "lib_docs/SBOLDocument.js~SBOLDocument#functionalComponent",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#genericlocation",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-genericLocation",
    "lib_docs/SBOLDocument.js~SBOLDocument#genericLocation",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#interaction",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-interaction",
    "lib_docs/SBOLDocument.js~SBOLDocument#interaction",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#interactions",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-interactions",
    "lib_docs/SBOLDocument.js~SBOLDocument#interactions",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#link",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-link",
    "lib_docs/SBOLDocument.js~SBOLDocument#link",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#loadrdf",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-loadRDF",
    "lib_docs/SBOLDocument.js~SBOLDocument#loadRDF",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#lookupuri",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-lookupURI",
    "lib_docs/SBOLDocument.js~SBOLDocument#lookupURI",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#lookupuris",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-lookupURIs",
    "lib_docs/SBOLDocument.js~SBOLDocument#lookupURIs",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#mapuri",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-mapURI",
    "lib_docs/SBOLDocument.js~SBOLDocument#mapURI",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#mapping",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-mapping",
    "lib_docs/SBOLDocument.js~SBOLDocument#mapping",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#mappings",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-mappings",
    "lib_docs/SBOLDocument.js~SBOLDocument#mappings",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#model",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-model",
    "lib_docs/SBOLDocument.js~SBOLDocument#model",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#models",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-models",
    "lib_docs/SBOLDocument.js~SBOLDocument#models",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#module",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-module",
    "lib_docs/SBOLDocument.js~SBOLDocument#module",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#moduledefinition",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-moduleDefinition",
    "lib_docs/SBOLDocument.js~SBOLDocument#moduleDefinition",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#moduledefinitions",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-moduleDefinitions",
    "lib_docs/SBOLDocument.js~SBOLDocument#moduleDefinitions",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#modules",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-modules",
    "lib_docs/SBOLDocument.js~SBOLDocument#modules",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#participation",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-participation",
    "lib_docs/SBOLDocument.js~SBOLDocument#participation",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#participations",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-participations",
    "lib_docs/SBOLDocument.js~SBOLDocument#participations",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#range",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-range",
    "lib_docs/SBOLDocument.js~SBOLDocument#range",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#sequence",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-sequence",
    "lib_docs/SBOLDocument.js~SBOLDocument#sequence",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#sequenceannotation",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-sequenceAnnotation",
    "lib_docs/SBOLDocument.js~SBOLDocument#sequenceAnnotation",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#sequenceannotations",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-sequenceAnnotations",
    "lib_docs/SBOLDocument.js~SBOLDocument#sequenceAnnotations",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#sequenceconstraint",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-sequenceConstraint",
    "lib_docs/SBOLDocument.js~SBOLDocument#sequenceConstraint",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#sequenceconstraints",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-sequenceConstraints",
    "lib_docs/SBOLDocument.js~SBOLDocument#sequenceConstraints",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#sequences",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-sequences",
    "lib_docs/SBOLDocument.js~SBOLDocument#sequences",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#serializejson",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-serializeJSON",
    "lib_docs/SBOLDocument.js~SBOLDocument#serializeJSON",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#serializexml",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-serializeXML",
    "lib_docs/SBOLDocument.js~SBOLDocument#serializeXML",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#todisplaylist",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-toDisplayList",
    "lib_docs/SBOLDocument.js~SBOLDocument#toDisplayList",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#unmapuri",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-method-unmapURI",
    "lib_docs/SBOLDocument.js~SBOLDocument#unmapURI",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument#unresolveduris",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#instance-get-unresolvedURIs",
    "lib_docs/SBOLDocument.js~SBOLDocument#unresolvedURIs",
    "member"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument.loadrdf",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#static-method-loadRDF",
    "lib_docs/SBOLDocument.js~SBOLDocument.loadRDF",
    "method"
  ],
  [
    "lib_docs/sboldocument.js~sboldocument.loadrdffile",
    "class/lib_docs/SBOLDocument.js~SBOLDocument.html#static-method-loadRDFFile",
    "lib_docs/SBOLDocument.js~SBOLDocument.loadRDFFile",
    "method"
  ],
  [
    "lib_docs/sequence.js",
    "file/lib_docs/Sequence.js.html",
    "lib_docs/Sequence.js",
    "file"
  ],
  [
    "lib_docs/sequence.js~sequence#constructor",
    "class/lib_docs/Sequence.js~Sequence.html#instance-constructor-constructor",
    "lib_docs/Sequence.js~Sequence#constructor",
    "method"
  ],
  [
    "lib_docs/sequence.js~sequence#elements",
    "class/lib_docs/Sequence.js~Sequence.html#instance-set-elements",
    "lib_docs/Sequence.js~Sequence#elements",
    "member"
  ],
  [
    "lib_docs/sequence.js~sequence#elements",
    "class/lib_docs/Sequence.js~Sequence.html#instance-get-elements",
    "lib_docs/Sequence.js~Sequence#elements",
    "member"
  ],
  [
    "lib_docs/sequence.js~sequence#encoding",
    "class/lib_docs/Sequence.js~Sequence.html#instance-set-encoding",
    "lib_docs/Sequence.js~Sequence#encoding",
    "member"
  ],
  [
    "lib_docs/sequence.js~sequence#encoding",
    "class/lib_docs/Sequence.js~Sequence.html#instance-get-encoding",
    "lib_docs/Sequence.js~Sequence#encoding",
    "member"
  ],
  [
    "lib_docs/sequenceannotation.js",
    "file/lib_docs/SequenceAnnotation.js.html",
    "lib_docs/SequenceAnnotation.js",
    "file"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#addlocation",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-method-addLocation",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#addLocation",
    "method"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#component",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-get-component",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#component",
    "member"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#component",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-set-component",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#component",
    "member"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#constructor",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-constructor-constructor",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#constructor",
    "method"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#link",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-method-link",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#link",
    "method"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#locations",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-get-locations",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#locations",
    "member"
  ],
  [
    "lib_docs/sequenceannotation.js~sequenceannotation#ranges",
    "class/lib_docs/SequenceAnnotation.js~SequenceAnnotation.html#instance-get-ranges",
    "lib_docs/SequenceAnnotation.js~SequenceAnnotation#ranges",
    "member"
  ],
  [
    "lib_docs/sequenceconstraint.js",
    "file/lib_docs/SequenceConstraint.js.html",
    "lib_docs/SequenceConstraint.js",
    "file"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#constructor",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-constructor-constructor",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#constructor",
    "method"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#link",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-method-link",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#link",
    "method"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#object",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-set-object",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#object",
    "member"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#object",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-get-object",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#object",
    "member"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#restriction",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-set-restriction",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#restriction",
    "member"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#restriction",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-get-restriction",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#restriction",
    "member"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#subject",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-set-subject",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#subject",
    "member"
  ],
  [
    "lib_docs/sequenceconstraint.js~sequenceconstraint#subject",
    "class/lib_docs/SequenceConstraint.js~SequenceConstraint.html#instance-get-subject",
    "lib_docs/SequenceConstraint.js~SequenceConstraint#subject",
    "member"
  ],
  [
    "lib_docs/load/rdf/loadcollection.js",
    "file/lib_docs/load/rdf/loadCollection.js.html",
    "lib_docs/load/rdf/loadCollection.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadcomponent.js",
    "file/lib_docs/load/rdf/loadComponent.js.html",
    "lib_docs/load/rdf/loadComponent.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadcomponentdefinition.js",
    "file/lib_docs/load/rdf/loadComponentDefinition.js.html",
    "lib_docs/load/rdf/loadComponentDefinition.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadcut.js",
    "file/lib_docs/load/rdf/loadCut.js.html",
    "lib_docs/load/rdf/loadCut.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadfunctionalcomponent.js",
    "file/lib_docs/load/rdf/loadFunctionalComponent.js.html",
    "lib_docs/load/rdf/loadFunctionalComponent.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadgenericlocation.js",
    "file/lib_docs/load/rdf/loadGenericLocation.js.html",
    "lib_docs/load/rdf/loadGenericLocation.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadidentified.js",
    "file/lib_docs/load/rdf/loadIdentified.js.html",
    "lib_docs/load/rdf/loadIdentified.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadinteraction.js",
    "file/lib_docs/load/rdf/loadInteraction.js.html",
    "lib_docs/load/rdf/loadInteraction.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadmapping.js",
    "file/lib_docs/load/rdf/loadMapping.js.html",
    "lib_docs/load/rdf/loadMapping.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadmodel.js",
    "file/lib_docs/load/rdf/loadModel.js.html",
    "lib_docs/load/rdf/loadModel.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadmodule.js",
    "file/lib_docs/load/rdf/loadModule.js.html",
    "lib_docs/load/rdf/loadModule.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadmoduledefinition.js",
    "file/lib_docs/load/rdf/loadModuleDefinition.js.html",
    "lib_docs/load/rdf/loadModuleDefinition.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadparticipation.js",
    "file/lib_docs/load/rdf/loadParticipation.js.html",
    "lib_docs/load/rdf/loadParticipation.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadrdf.js",
    "file/lib_docs/load/rdf/loadRDF.js.html",
    "lib_docs/load/rdf/loadRDF.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadrange.js",
    "file/lib_docs/load/rdf/loadRange.js.html",
    "lib_docs/load/rdf/loadRange.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadsequence.js",
    "file/lib_docs/load/rdf/loadSequence.js.html",
    "lib_docs/load/rdf/loadSequence.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadsequenceannotation.js",
    "file/lib_docs/load/rdf/loadSequenceAnnotation.js.html",
    "lib_docs/load/rdf/loadSequenceAnnotation.js",
    "file"
  ],
  [
    "lib_docs/load/rdf/loadsequenceconstraint.js",
    "file/lib_docs/load/rdf/loadSequenceConstraint.js.html",
    "lib_docs/load/rdf/loadSequenceConstraint.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializecollection.js",
    "file/lib_docs/serialize/json/serializeCollection.js.html",
    "lib_docs/serialize/json/serializeCollection.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializecomponent.js",
    "file/lib_docs/serialize/json/serializeComponent.js.html",
    "lib_docs/serialize/json/serializeComponent.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializecomponentdefinition.js",
    "file/lib_docs/serialize/json/serializeComponentDefinition.js.html",
    "lib_docs/serialize/json/serializeComponentDefinition.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializefunctionalcomponent.js",
    "file/lib_docs/serialize/json/serializeFunctionalComponent.js.html",
    "lib_docs/serialize/json/serializeFunctionalComponent.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializeidentified.js",
    "file/lib_docs/serialize/json/serializeIdentified.js.html",
    "lib_docs/serialize/json/serializeIdentified.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializeinteraction.js",
    "file/lib_docs/serialize/json/serializeInteraction.js.html",
    "lib_docs/serialize/json/serializeInteraction.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializejson.js",
    "file/lib_docs/serialize/json/serializeJSON.js.html",
    "lib_docs/serialize/json/serializeJSON.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializelocation.js",
    "file/lib_docs/serialize/json/serializeLocation.js.html",
    "lib_docs/serialize/json/serializeLocation.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializemodel.js",
    "file/lib_docs/serialize/json/serializeModel.js.html",
    "lib_docs/serialize/json/serializeModel.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializemoduledefinition.js",
    "file/lib_docs/serialize/json/serializeModuleDefinition.js.html",
    "lib_docs/serialize/json/serializeModuleDefinition.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializeparticipation.js",
    "file/lib_docs/serialize/json/serializeParticipation.js.html",
    "lib_docs/serialize/json/serializeParticipation.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializesequence.js",
    "file/lib_docs/serialize/json/serializeSequence.js.html",
    "lib_docs/serialize/json/serializeSequence.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializesequenceannotation.js",
    "file/lib_docs/serialize/json/serializeSequenceAnnotation.js.html",
    "lib_docs/serialize/json/serializeSequenceAnnotation.js",
    "file"
  ],
  [
    "lib_docs/serialize/json/serializesequenceconstraint.js",
    "file/lib_docs/serialize/json/serializeSequenceConstraint.js.html",
    "lib_docs/serialize/json/serializeSequenceConstraint.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializeannotation.js",
    "file/lib_docs/serialize/xml/serializeAnnotation.js.html",
    "lib_docs/serialize/xml/serializeAnnotation.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializecollection.js",
    "file/lib_docs/serialize/xml/serializeCollection.js.html",
    "lib_docs/serialize/xml/serializeCollection.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializecomponent.js",
    "file/lib_docs/serialize/xml/serializeComponent.js.html",
    "lib_docs/serialize/xml/serializeComponent.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializecomponentdefinition.js",
    "file/lib_docs/serialize/xml/serializeComponentDefinition.js.html",
    "lib_docs/serialize/xml/serializeComponentDefinition.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializefunctionalcomponent.js",
    "file/lib_docs/serialize/xml/serializeFunctionalComponent.js.html",
    "lib_docs/serialize/xml/serializeFunctionalComponent.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializeidentified.js",
    "file/lib_docs/serialize/xml/serializeIdentified.js.html",
    "lib_docs/serialize/xml/serializeIdentified.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializeinteraction.js",
    "file/lib_docs/serialize/xml/serializeInteraction.js.html",
    "lib_docs/serialize/xml/serializeInteraction.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializelocation.js",
    "file/lib_docs/serialize/xml/serializeLocation.js.html",
    "lib_docs/serialize/xml/serializeLocation.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializemapping.js",
    "file/lib_docs/serialize/xml/serializeMapping.js.html",
    "lib_docs/serialize/xml/serializeMapping.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializemodel.js",
    "file/lib_docs/serialize/xml/serializeModel.js.html",
    "lib_docs/serialize/xml/serializeModel.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializemodule.js",
    "file/lib_docs/serialize/xml/serializeModule.js.html",
    "lib_docs/serialize/xml/serializeModule.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializemoduledefinition.js",
    "file/lib_docs/serialize/xml/serializeModuleDefinition.js.html",
    "lib_docs/serialize/xml/serializeModuleDefinition.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializeparticipation.js",
    "file/lib_docs/serialize/xml/serializeParticipation.js.html",
    "lib_docs/serialize/xml/serializeParticipation.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializesequence.js",
    "file/lib_docs/serialize/xml/serializeSequence.js.html",
    "lib_docs/serialize/xml/serializeSequence.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializesequenceannotation.js",
    "file/lib_docs/serialize/xml/serializeSequenceAnnotation.js.html",
    "lib_docs/serialize/xml/serializeSequenceAnnotation.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializesequenceconstraint.js",
    "file/lib_docs/serialize/xml/serializeSequenceConstraint.js.html",
    "lib_docs/serialize/xml/serializeSequenceConstraint.js",
    "file"
  ],
  [
    "lib_docs/serialize/xml/serializexml.js",
    "file/lib_docs/serialize/xml/serializeXML.js.html",
    "lib_docs/serialize/xml/serializeXML.js",
    "file"
  ],
  [
    "lib_docs/util.js",
    "file/lib_docs/util.js.html",
    "lib_docs/util.js",
    "file"
  ]
]